# Pre-commit hooks for code quality
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Python: Ruff (linting + formatting)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  # JavaScript/TypeScript: ESLint + Prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx|jsx)$
        types: [file]
        additional_dependencies:
          - eslint@9.17.0
          - typescript-eslint@8.18.2
          - '@eslint/js@9.17.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        files: \.(js|ts|tsx|jsx|json|md|yml|yaml)$
        exclude: ^(package-lock\.json|pnpm-lock\.yaml)$

  # General file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^teacher/.*/solutions/
      - id: end-of-file-fixer
        exclude: ^teacher/.*/solutions/
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]

  # Commit message linting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, --force-scope]

  # Security: Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: ^(package-lock\.json|\.secrets\.baseline)$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(node_modules|teacher/.*/solutions/)

# Configuration
default_language_version:
  python: python3.12
  node: '20.18.1'

# Skip hooks for specific scenarios
ci:
  skip: [eslint, prettier]  # Run these in CI separately
